In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.transpose(arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])